### PR TITLE
Add sunfish maintainer

### PR DESCRIPTION
**Pull request by xstefen**
Someone else will have to deal with any XDA or other tomfoolery, I dont do that stuff

### CODE REVIEW

**Comment by xstefen** [comment]
https://gist.github.com/xstefen/125392afbf2639bf3f09a2656b4401e8

**Comment by xstefen** [comment]
https://github.com/ResurrectionRemix/platform_manifest/pull/148

**Comment by varund7726** [comment]
We need same person for xda . sorry then

**Comment by xstefen** [comment]
alright ill try it out, but if i get overwhelmed with retards im just going to take my time responding

**Comment by varund7726** [comment]
Of course . that's understandable . no rush.  Can I have your telegram handle ?

**Pull request merged**
