### PR TITLE
Add Redmi Note 7 Pro (Violet) Maintainers

### PR DESCRIPTION
**Pull request by prajwal-walia**

### CODE REVIEW

**Comment by funeralfrog** [comment]
You can contact us on Telegram: 
Prajwal: https://t.me/Wally_West_The_Flash
Nitish: https://t.me/nerdfail

**Comment by varund7726** [comment]
All working ok?

**Comment by prajwal-walia** [comment]
Under testing right now will update when done testing
basic stuff works ofc

**Comment by varund7726** [comment]
ok

**Comment by varund7726** [comment]
Actually we have one more guy who has reported that his builds have been tested and are ready for a release so im going to have to close this. Sorry guys. You are free to maintain unofficial builds

**Comment by varund7726** [comment]
you guys are free to contribute and help him maintain. please discuss with him first

**Comment by prajwal-walia** [comment]
> 
> 
> you guys are free to contribute and help him maintain. please discuss with him first

Naa we are good let him do him

**Pull request closed without merging**
