### PR TITLE
Fix Magisk code. As well as code cleanup

### PR DESCRIPTION
**Pull request by ghost**
Pretty much self explanatory. Decided to throw away my idea but in the process found a few issues. Sorry I didnt do a few of these things properly in the first place.

### CODE REVIEW

**Comment by ghost** [comment]
Should I go ahead and drop this?

**Comment by varund7726** [comment]
Nope why? We are just a bit busy testing 7.1.2 merge .then we will review this .please let it be open .I'll look into it for sure

**Comment by ghost** [comment]
Im new to Pull Request. Thats fine. Take your time.

**Comment by ghost** [comment]
Just I side note. The commits for blinking LED for Shamu are gone. Not sure if thats a result of a --force push command

**Comment by varund7726** [comment]
The commits for shamu led were not merged in settings. In fact you pushed them on device tree and they are still there

**Comment by APOPHIS9283** [comment]
Weird github seems to be playing tricks on me. I just compiled yesterday even did --force-sybc and it doesnt have the option.

**Comment by APOPHIS9283** [comment]
--force-sync

**Comment by ghost** [comment]
Yeah I know not in settings but in device/motoshamu and kernel/moto/shamu

I am going to erase my whole folder and start over with a fresh repo sync

**Comment by ghost** [comment]
Not sure what happened, Github error. Sorry for mentioning those commits werent there. I clean repo sync'ed and all is well. Not sure what happened

**Comment by varund7726** [comment]
looks like he wants to ignore our posts. no point in keeping this pull request then . i was being nice to him but THIS is how he "repays" us.

**Pull request closed without merging**
