### PR TITLE
Add Redmi Note 4

### PR DESCRIPTION
**Pull request by harveyspectar**

### CODE REVIEW

**Comment by varund7726** [comment]
Xda thread? device sources?

**Comment by harveyspectar** [comment]
https://github.com/harveyspectar/device_xiaomi_mido
https://github.com/KudProject/kernel_msm-4.9
https://github.com/KudProject/proprietary_vendor_xiaomi

**Comment by varund7726** [comment]
ok can you send your Telegram?

**Comment by varund7726** [comment]
@akhilnarang will approve once he has time

**Comment by harveyspectar** [comment]
https://t.me/Harvey_Spectar
I have contacted you on telegram

**Comment by akhilnarang** [comment]
@harveyspectar everything is working fine?

**Comment by harveyspectar** [comment]
Yup

**Pull request merged**
