### PR TITLE
add vs985/ls990/d850/f400 maintainer

### PR DESCRIPTION
**Pull request by oadam11**

### CODE REVIEW

**Comment by varund7726** [comment]
Are these devices added in fragment as well?

**Comment by oadam11** [comment]
Ya. I believe d852 is the only one missing. I don't mind building for it if need be

**Comment by varund7726** [comment]
No I mean the devices you newly added should be present in res/XML/device_maintainers_fragment.xml

**Comment by oadam11** [comment]
done. https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/pull/597

**Pull request merged**
