### PR TITLE
Updated Hydrogen Maintainer

### PR DESCRIPTION
**Pull request by sarthakmalla**

### CODE REVIEW

**Comment by varund7726** [comment]
What happened to the previous maintainer

**Comment by sarthakmalla** [comment]
He have discontinued

**Comment by varund7726** [comment]
Did u ask him?

**Comment by sarthakmalla** [comment]
screenshot_20170809-130232

**Comment by varund7726** [comment]
ok then

**Comment by sarthakmalla** [comment]
Are you on telegram

**Pull request merged**
