### PR TITLE
Added Nougat Maintainer For LeEco Le 2 (s2)

### PR DESCRIPTION
**Pull request by rishabhrao**
Signed-off-by: rishabhrao <admin@rishabhrao.net>

### CODE REVIEW

**Comment by rishabhrao** [comment]
I maintain Unofficial Builds of RR Nougat 7.1.1 for LeEco Le 2.

XDA Post Here: https://forum.xda-developers.com/le-2/development/resurrectionremix-t3546376/

**Comment by rishabhrao** [comment]
Thanks a Lot Sir.

**Comment by varund7726** [comment]
No problem , if you want to be added to our maintainers slack channel , please send me your email , I will send you an invite

**Comment by rishabhrao** [comment]
Sure Sir.

My Email: admin@rishabhrao.net

**Pull request merged**
