### PR TITLE
Update resurrection_device_maintainers_strings.xml

### PR DESCRIPTION
**Pull request by BH36BE**
Device tree:
https://github.com/ikeh045/device_xiaomay_kenzo

Kernel:
https://github.com/ikeh045/kernel_xiaomay_msm8956

Vendor:
https://github.com/ikeh045/vendor_xiaomay_kenzo

Telegram:https://t.me/BH36B

### CODE REVIEW

**Comment by varund7726** [comment]
Kenzo = wasabi?

**Comment by varund7726** [comment]
Also need to add in fragment

**Review by BH36BE — COMMENTED** [review]
how to add the fragment

**Comment by varund7726** [comment]
It's in res/XML

See how other maintainers have done it

**Comment by ikeh045** [comment]
Done sir https://github.com/ikeh045/Resurrection_packages_apps_Settings/commit/fc070b93caeee5b1719eb007a7198eef2c0f7b5e

**Comment by BH36BE** [comment]
Done sir

**Comment by varund7726** [comment]
Sorry please make both files in 1 pull request . Thanks

**Pull request closed without merging**
