### PR TITLE
Add Maintainer for LG G2 (Sprint) LS980 variant

### PR DESCRIPTION
**Pull request by kaanyigitkulahli**

### CODE REVIEW

**Comment by kaanyigitkulahli** [comment]
@westcripp

**Comment by varund7726** [comment]
Wrong . add the device in fragment as well.

**Comment by kaanyigitkulahli** [comment]
What was wrong?

**Comment by varund7726** [comment]
You need to make it like this https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/51a82c806d1437470aaae528f6d436eba317832f

**Comment by kaanyigitkulahli** [comment]
İs this true now ?

**Comment by varund7726** [comment]
Yup

**Comment by kaanyigitkulahli** [comment]
Thanks :)

**Pull request merged**
