### PR TITLE
add ZTE Axon7

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by varund7726 — COMMENTED** [review]
Please add device to fragment as well

**Comment by akhilnarang** [comment]
@aclegg2011 do you want to maintain it or not?

**Comment by ghost** [comment]
Yes I do

**Comment by varund7726** [comment]
Then add device to fragment please like I said

**Comment by ghost** [comment]
Actually, upon further review, I've decided to move on from RR. After march 2 I'm dropping official support for N7 (deb/flo), axon7, and g3 (d851)

**Comment by akhilnarang** [comment]
After march 2nd? That was a long time ago.....

**Comment by varund7726** [comment]
Ok @aclegg2011 any reason why

**Pull request closed without merging**
