### PR TITLE
Settings: Read Moto Maxx-Turbo, Droid Turbo Maintainer also clean up …

### PR DESCRIPTION
**Pull request by fgl27**
…duplicated strings

I believed is not need two of the same...

I remove the duplicated one that has no maintainer name.

### CODE REVIEW

**Comment by varund7726** [comment]
Please remove all other commits and make pull request again

**Comment by fgl27** [comment]
Fix it.

**Comment by varund7726** [comment]
But omkar Shinde is maintaining bullhead.don't remove any pls

**Comment by varund7726** [comment]
If there is a maintainer later on , they will add their names .hence its necessary to keep it here

**Comment by fgl27** [comment]
did you not understand the duplicated part???

https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/blob/nougat/res/values/resurrection_device_maintainers_strings.xml#L444

https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/blob/nougat/res/values/resurrection_device_maintainers_strings.xml#L462

I'm wrong here?

Sorry it doesn't seems to me, please read my first comment i edit it.

**Comment by varund7726** [comment]
OK got it

**Pull request merged**
