### PR TITLE
added zuk Z2 plus

### PR DESCRIPTION
**Pull request by MRTHAKER**

### CODE REVIEW

**Comment by akhilnarang** [comment]
Category should be per OEM, not per device

Just for zuk, not for zuk z2

**Comment by MRTHAKER** [comment]
okay fixed now..removed zuk z2 from category...

**Comment by varund7726** [comment]
device_Zuk_Z2_plus should be device_Zuk_Z2

**Comment by MRTHAKER** [comment]
okay i fix it, and bro can you accept my hangouts invitation please..

**Pull request merged**
