### PR TITLE
Maintainers: add Samsung Galaxy Note 4 (Exynos)

### PR DESCRIPTION
**Pull request by sunsettrack4**
http://forum.xda-developers.com/note-4/development/rom-resurrectionremix-v5-6-3-t3313724

### CODE REVIEW

**Comment by akhilnarang** [comment]
As I said on the previous pull request, add in the fragment too

**Comment by westcripp** [comment]
to here https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/blob/a11d6779e6a9645d8d905ab14a0cff75e2cd8b77/res/xml/device_maintainers_fragment.xml

**Comment by sunsettrack4** [comment]
Yes, I'm editing that file right now.

**Comment by sunsettrack4** [comment]
Done.

**Comment by sunsettrack4** [comment]
Please merge...

**Pull request merged**
