### PR TITLE
Add violet to official devices

### PR DESCRIPTION
**Pull request by Joker-V2**
Device tree: https://github.com/Joker-V2/device_xiaomi_violet_rr
Common DT: https://github.com/Joker-V2/android_device_xiaomi_sm6150-common
Vendor: https://gitlab.com/Joker-V2/proprietary_vendor_xiaomi
Kernel: https://github.com/Joker-V2/kernel_xiaomi_sm6150

### CODE REVIEW

**Comment by Joker-V2** [comment]
Telegram
Nipin NA: https://t.me/Joker_V2_0
Released unofficial build link: https://t.me/redminote7proupdates/205 (Violet official channel)

**Comment by varund7726** [comment]
we already have someone who applied before https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/pull/1143

**Comment by Joker-V2** [comment]
They havent pushed any builds yet sir..check violet official channel and see my work..

**Comment by Joker-V2** [comment]
My build is tested and stable enough.. Everything working fine.. Also posted to public channel and users using it

**Comment by varund7726** [comment]
merged. Will add you to TG group

**Pull request merged**
