### PR TITLE
Update resurrection_device_maintainers_strings.xml

### PR DESCRIPTION
**Pull request by ahmedshaikh123**
Added Maintainer Name for X01BD

### CODE REVIEW

**Comment by varund7726** [comment]
You need to add in fragment like this https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/pull/1204/files

**Comment by varund7726** [comment]
Otherwise your name won't show
Make a new commit and include both file changes in 1 commit
Thanks

**Comment by ahmedshaikh123** [comment]
Sir,
Thats Already Present

**Comment by varund7726** [comment]
Then adding new strings will cause build error. modify existing strings

**Pull request closed without merging**
