### PR TITLE
Add Nextbit Robin as Official

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@harveyspectar what's wrong with the pull request?It's been a week now.

**Comment by varund7726** [comment]
I have mentioned in the comments what's wrong

**Comment by ghost** [comment]
@varund7726 I'm sorry but I did what you have told me there in the last pull request.I followed what other just did.Forked Resurrection_packages_apps_Settings added device and pull request from there.Isn't it the correct way?

**Comment by varund7726** [comment]
You have placed the following code in the very beginning of the file which is wrong and will cause settings FC 

You need to place it where the rest of these preferences are 

<Preference
       android:id="@+id/device_nextbit_ether"
        android:icon="@drawable/phone_tint"  
        android:summary="@string/device_nextbit_ether_summary"
        android:selectable="false" 
        android:title="@string/device_nextbit_ether/>

**Comment by ghost** [comment]
@varund7726  Now It's okay.

**Comment by varund7726** [comment]
N in Nextbit should be small not capital 
Compiler is case sensitive

**Comment by ghost** [comment]
@varund7726  Okay,I apology for many mistakes.I think it's perfect now.

**Pull request merged**
