### PR TITLE
Moto X 2014 Maintainer Xda Thread -http://forum.xda-developers.com/mo…

### PR DESCRIPTION
**Pull request by omkxr**
…to-x-2014/development/rom-resurrection-remix-v5-4-2-t3093506

### CODE REVIEW

**Comment by matteasu** [comment]
@varund7726 this commit merge removed my nickname added on this pull request https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/pull/298/

**Comment by omkxr** [comment]
yeah that was weird i didnt deleted it :P

**Comment by akhilnarang** [comment]
oops @Matoxxi  will add again

**Comment by akhilnarang** [comment]
@Megatron007 coz you forked before we merged his I guess XD

**Comment by akhilnarang** [comment]
@Matoxxi https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/6b659d9ab0edd24f2a5d35320b7b1b0837706a92

**Comment by matteasu** [comment]
@akhilnarang  thanks :)

**Pull request merged**
