### PR TITLE
Settings: add option to set color for statusbar clock [1/2]

### PR DESCRIPTION
**Pull request by mobspyguy**
I add colorpicker into statusbar options to select statusbar clock color

### CODE REVIEW

**Comment by arif1413** [comment]
gfr

**Comment by varund7726** [comment]
who are you? stop spamming

**Comment by thecipherman** [comment]
Please sir Redesign VoLTE symbol as LineageOS has or any different because this is smaller than network and wifi signal and looks good. I didn't find correct place to request so I requested here, Sorry for this sir

**Comment by thecipherman** [comment]
*not looks good

**Comment by akhilnarang** [comment]
LineageOS dosen't even have a VoLTE icon

And this is the wrong place, post on g+ or telegram chat

**Pull request closed without merging**
