### PR TITLE
Add Jason maintainer 

### PR DESCRIPTION
**Pull request by enweazudaniel**
XDA Thread: https://forum.xda-developers.com/mi-note-3/development/resurrection-remix-os-q-2020-unofficial-t4150961
Common tree: https://github.com/LineageOS/android_device_xiaomi_sdm660-common
Vendor: https://gitlab.com/the-muppets/proprietary_vendor_xiaomi 
Device: https://github.com/LineageOS/android_device_xiaomi_jason 
Kernel: https://github.com/LineageOS/android_kernel_xiaomi_sdm660 

Telegram: https://t.me/dandollar1

Email: enweazu.daniel@gmail.com

### CODE REVIEW

**Comment by enweazudaniel** [comment]
Please sir any problem it my PR?

**Comment by varund7726** [comment]
Conflicts

**Comment by enweazudaniel** [comment]
Which of the commits sir? At first submisson there were no conflicts

**Comment by enweazudaniel** [comment]
well at first submission there were no conflicts

**Pull request closed without merging**
