### PR TITLE
Add Lavender Maintainer

### PR DESCRIPTION
**Pull request by Bagualisson**
Device tree: https://github.com/AlissonGrizotti/device_xiaomi_lavender/tree/rr
Kernel tree: https://github.com/AlissonGrizotti/kernel_xiaomi_lavender/tree/ten-oc
Vendor tree: https://github.com/AlissonGrizotti/vendor_xiaomi_lavender

Signed-off-by: AlissonGrizotti <alisson1397@hotmail.com>

### CODE REVIEW

**Comment by varund7726** [comment]
Are you the same one who contacted me on TG?

**Comment by Bagualisson** [comment]
No

**Comment by Bagualisson** [comment]
My Telegram is @Bagualisson

**Comment by varund7726** [comment]
Sorry then I already have someone who contacted me before hand. Will confirm if he is continuing

**Comment by Bagualisson** [comment]
Okay, I wait, I contacted the Akhil Narang on the previous Telegram, if I had known, I would have contacted you, but I will wait for amsiosamet confirmation, I like RR 😁

**Comment by varund7726** [comment]
Sorry have to give to the other one since he had approached me first. You are free to maintain unofficial

**Comment by Bagualisson** [comment]
No problem, I'll be willing to if you ever need 😁

**Pull request closed without merging**
