### PR TITLE
maintainers: Add new oneplus2 device maintainer 'regalstreak'

### PR DESCRIPTION
**Pull request by regalstreak**
Please Merge. Thanks!

### CODE REVIEW

**Comment by akhilnarang** [comment]
@regalstreak  sorry, @varund7726  is the maintainer, he's busy, so hasn't posted a build yet

**Comment by regalstreak** [comment]
@akhilnarang check mail (check spam folder too)

**Comment by regalstreak** [comment]
@akhilnarang @varund7726 
Atleast ask him before closing the PR :|

http://forum.xda-developers.com/oneplus-2/development/rom-resurrection-remix-v5-6-0-t3277901/page4

screenshot from 2015-12-26 18 16 36

**Comment by akhilnarang** [comment]
OK fine

**Pull request merged**
