### PR TITLE
Official for Osprey

### PR DESCRIPTION
**Pull request by Subinsmani**

### CODE REVIEW

**Comment by anisnoorudheen** [comment]
Pls appreove him ... Waiting for rr official on my bird

**Comment by akhilnarang** [comment]
What's that `Arcade` in the brackets for, remove that too

**Comment by Subinsmani** [comment]
Thank you for the response sir...
Yes i removed Arcade..

**Comment by akhilnarang** [comment]
@Subinsmani what's your telegram username?

**Comment by Subinsmani** [comment]
@Subinsmani...
😂

**Pull request merged**
