### PR TITLE
Update pt-PT cm_strings

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by akhilnarang** [comment]
LineageOS crowdin has these?

**Comment by ghost** [comment]
Yes:
captura de ecra 2018-06-13 as 13 32 53


/res/values/cm_strings.xml: https://github.com/LineageOS/android_packages_apps_Settings/blob/lineage-15.1/res/values/cm_strings.xml

/res/values-pt-rPT/cm_strings.xml: https://github.com/LineageOS/android_packages_apps_Settings/blob/lineage-15.1/res/values-pt-rPT/cm_strings.xml


But they actually have some new different strings.

**Comment by ghost** [comment]
@akhilnarang 
Can you help me to find where this is being used so I can make the strings translatable?
05_screenshot_advanced_settings_20180520-183516

**Comment by akhilnarang** [comment]
@tfae send screenshot of the main screen in english

**Comment by ghost** [comment]
Those are the actions for the OnePlus' notification slider positions.
screenshot_advanced_settings_20180616-192900
screenshot_advanced_settings_20180616-192904

**Comment by akhilnarang** [comment]
Ah those, I have some strings translated for that, I'll push soon

**Comment by ghost** [comment]
Great!

**Comment by ghost** [comment]
Hi @akhilnarang! Any news about this?
I would really like to have the next build finally fully translated because of my OCD :P

**Comment by akhilnarang** [comment]
@tfae will definitely try to get them included by next build!

**Comment by akhilnarang** [comment]
Otherwise if you want, you can pull request here
https://github.com/ResurrectionRemix-Devices/android_device_oppo_common/tree/oreo

**Comment by ghost** [comment]
Done! :)

**Pull request merged**
