### PR TITLE
M9 :Update maintainer

### PR DESCRIPTION
**Pull request by onexmaster**
irocevo was maintaining the sprint version and i am maintaining the global version

### CODE REVIEW

**Comment by varund7726** [comment]
Has the previous maintainer agreed to stopping development?

**Comment by onexmaster** [comment]
Actually not ...but i would suggest to split out sprint and international version . I will send a pm to him about this topic

**Comment by varund7726** [comment]
plz confirm and let me know

**Comment by onexmaster** [comment]
Yes sure

**Pull request closed without merging**
