### PR TITLE
Settings: German translation (I)

### PR DESCRIPTION
**Pull request by sunsettrack4**
Maybe you can add me to the collaborators list for this repository.

### CODE REVIEW

**Comment by akhilnarang** [comment]
@sunsettrack4 have you tested building with these?
Just wanna confirm no derps in it

**Comment by sunsettrack4** [comment]
I need 4-6 hours to do that. I compared the original file and the German one, the strings are identical.

**Comment by varund7726** [comment]
once this request is merged you will be added automatically as colaborator

**Comment by sunsettrack4** [comment]
So why do I get this error:
error on line 1954 at column 13: Opening and ending tag mismatch: string line 0 and resources
I don't have line 0 in this file.

**Pull request closed without merging**
