### PR TITLE
Quick Settings icon toggle animation

### PR DESCRIPTION
**Pull request by dutchman1990**
This will add animation in the quick settings icons during toggle.

### CODE REVIEW

**Comment by varund7726** [comment]
this does not even belong here ....it belongs to arrays. and where is the frameworks base commit?
did you author this?
please give proper authorship and credits.!
and if you are planning to merge this please supply the full commit and proper code..this is incomplete !
authorship first

**Comment by dutchman1990** [comment]
Sorry my bad, I had a power cut during patch submission. Basically "Nicolas Dhouailly"
 has made that commit for DU. if you're OK with that then I'll add rest of the commit. Please let me know.

**Comment by varund7726** [comment]
Interesting . ..even if there was a power cut , arrays went in in XML :P

**Comment by dutchman1990** [comment]
I admit that was my my mistake during patch submission. human errror. :p

**Comment by varund7726** [comment]
No problem man .I said it in fun .cheers

**Comment by dutchman1990** [comment]
Ok, will submit the patch. Once I get home. Thanks for the "talk".

**Comment by varund7726** [comment]
👍 .don't forget to give authorship

**Pull request closed without merging**
