### PR TITLE
Add maintainer for Leeco Le 2

### PR DESCRIPTION
**Pull request by HridayHS**
Signed-off-by: Hriday Sharma <hridaysharma42@gmail.com>

### CODE REVIEW

**Comment by HridayHS** [comment]
I maintain unofficial build of RR-MM for leeco le 2 here: https://forum.xda-developers.com/le-2/development/rom-resurrectionremix-v5-7-4-t3529328

Only one bug are their, IR blaster not working.

**Comment by varund7726** [comment]
Make it official .

**Comment by HridayHS** [comment]
Thanks :)

**Comment by varund7726** [comment]
👍

**Pull request merged**
