### PR TITLE
Clear all

### PR DESCRIPTION
**Pull request by andrewwrightt**
Not sure if this is welcome but makes it clear that this is the color picker location for that icon. Moving so its below BG would be good but not sure how to do this.

### CODE REVIEW

**Comment by akhilnarang** [comment]
Can say FAB Color instead maybe

**Comment by akhilnarang** [comment]
Or FAB Icon Color

**Comment by varund7726** [comment]
Icon color is present

**Comment by andrewwrightt** [comment]
CHANGE
BUTTON BG / FAB BG
CLEAR ALL/FAB ICON 
?

**Comment by andrewwrightt** [comment]
Closed. Not needed.

**Pull request closed without merging**
