### PR TITLE
Create res/values-ja/rr_arrays.xml

### PR DESCRIPTION
**Pull request by lindwurm**
Localize `battery_bar_entries` and `qs_num_columns_entries`

### CODE REVIEW

**Comment by lindwurm** [comment]
some strings from rr_arrays.xml are not translatable on Crowdin, please merge it

**Comment by akhilnarang** [comment]
Will fix for crowdin soon

**Comment by akhilnarang** [comment]
https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/ced1ba4b8c28c0303e516fe04f10e244cf49a9d7
@lindwurm submit them to crowdin now please

**Comment by lindwurm** [comment]
Thanks @akhilnarang ! :+1:

**Pull request closed without merging**
