### PR TITLE
Added Xiaomi Mi A1 Maintainer

### PR DESCRIPTION
**Pull request by mountaser**

### CODE REVIEW

**Comment by akhilnarang** [comment]
Add in fragment...

**Comment by mountaser** [comment]
@akhilnarang  what do u mean ?

**Comment by mountaser** [comment]
like this ? @akhilnarang

**Comment by varund7726** [comment]
No dude @mountaser . you've made a pull request before. You know what a fragment is

**Comment by mountaser** [comment]
my bad forgot that its a new device xD @varund7726

**Pull request merged**
