### PR TITLE
Several updates

### PR DESCRIPTION
**Pull request by sunsettrack4**
Affected files:
res/values/rr_strings.xml
res/values-de/rr_strings.xml

Changes:
Delete duplicates
Simple updates

### CODE REVIEW

**Comment by sunsettrack4** [comment]
And please note that I'm still unable to push the changes directly without creating pull requests...

**Comment by akhilnarang** [comment]
That's normal

**Comment by varund7726** [comment]
@sunsettrack4 Why do u want to push without creating pull requests?
only 5 of us have access rights to the source
rest have to merge requests because we have to test before merging
we cannot allow our source to have commits pushed without our approval :)

**Comment by sunsettrack4** [comment]
I thought that once the first pull request was accepted, the person gets write access automatically. My fault...

**Pull request merged**
