### PR TITLE
Asus Zenfone 3 (Z012D) Maintainer

### PR DESCRIPTION
**Pull request by Cenk-ay**

### CODE REVIEW

**Comment by varund7726** [comment]
This commit and https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/pull/857 should be on one commit like I said . pls do so

**Comment by varund7726** [comment]
Like this https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/f6cc7a7c191972e5fa8f508a8fe77202dee12353

**Comment by varund7726** [comment]
This is a small kind of test to see if you guys know how to use github and to see if your able to keep up to the title of being official maintainers .

**Comment by Cenk-ay** [comment]
https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/pull/859

**Pull request closed without merging**
