### PR TITLE
Add Riva to official list

### PR DESCRIPTION
**Pull request by adi153**
Signed-off-by: adi153 <singhmanohar6699@gmail.com>[XDA](https://forum.xda-developers.com/xiaomi-redmi-5a/development/unofficial-resurrection-remix-t4146229) [Device Tree Source](https://github.com/adi153/rr_device_xiaomi_riva) [Device Kernel Source](https://github.com/SunnyRaj84348/android_kernel_xiaomi_msm8917)

### CODE REVIEW

**Comment by varund7726** [comment]
@akhilnarang

**Comment by akhilnarang** [comment]
Tested and everything is working fine?

**Comment by adi153** [comment]
Ofcourse everything working sir🙂

**Comment by varund7726** [comment]
Whats your telegram

**Comment by adi153** [comment]
> Whats your telegram

@adi153

> Whats your telegram

@adi153

**Pull request merged**
