### PR TITLE
Add Galaxy S5 LTE (klte)

### PR DESCRIPTION
**Pull request by saltyming**
Add klte only for now. Will add klte family devices later.
[XDA Thread](https://forum.xda-developers.com/galaxy-s5/unified-development/rom-resurrection-remix-q-galaxy-s5-klte-t4147267) 
[klte-common](https://github.com/FiestaLake/android_device_samsung_klte-common) 
[klte](https://github.com/FiestaLake/android_device_samsung_klte-common)
[msm8974-common](https://github.com/FiestaLake/android_device_samsung_msm8974-common) 
[Kernel](https://github.com/LineageOS/android_kernel_samsung_msm8974)

### CODE REVIEW

**Comment by varund7726** [comment]
Clean commit please. don't modify anything else.
Thanks

**Comment by saltyming** [comment]
> Clean commit please. don't modify anything else.
> Thanks

Done.

**Comment by varund7726** [comment]
Telegram ID?

**Comment by saltyming** [comment]
> Telegram ID?

FiestaLake

**Pull request merged**
