### PR TITLE
buttons: Add option to swap app switch and back buttons

### PR DESCRIPTION
**Pull request by regalstreak**
http://review.cyanogenmod.org/#/c/134892/
Thanks to grarak

### CODE REVIEW

**Comment by regalstreak** [comment]
If you can @varund7726 @akhilnarang please squash them in one commit.
My internet was sucking today hence had to edit on github directly

**Comment by akhilnarang** [comment]
We'll pick from gerrit
But there must be a reason he's abandoned it instead of pursuing it

**Comment by regalstreak** [comment]
@akhilnarang any update on this?

**Comment by akhilnarang** [comment]
Read my 2nd statement

**Pull request closed without merging**
