### PR TITLE
New maintainer for surya

### PR DESCRIPTION
**Pull request by MrAkells**
The official build has not been updated for many months. I am updating mine, unofficial. I want to make it official, some are leaving RR, because the official build has died, there are a lot of bugs in it.

https://4pda.to/forum/index.php?s=&showtopic=1006226&view=findpost&p=104719747

https://github.com/MrAkells/device_xiaomi_surya
https://github.com/lostark13/kernel_xiaomi_surya
https://github.com/MrAkells/vendor_xiaomi_surya

### CODE REVIEW

**Comment by enweazudaniel** [comment]
Did you contact the maintainer?

**Comment by Joker-V2** [comment]
Bruh 🤣🤣

**Comment by MrAkells** [comment]
> Did you contact the maintainer?

This is my first time doing this, so I'm not sure how to do it right. I wrote to the maintainer in the mail, I will wait for an answer.

**Comment by lostark13** [comment]
I will be updating the rom very soon.

**Pull request closed without merging**
