### PR TITLE
Update Korean translation

### PR DESCRIPTION
**Pull request by TheNoFace**

### CODE REVIEW

**Comment by TheNoFace** [comment]
Plus, have you checked your email? I sent an email about 2 days ago about adding new device for RR.

**Comment by akhilnarang** [comment]
@TheNoFace you can make pull request for that too in rr maintainer strings file

**Comment by TheNoFace** [comment]
@akhilnarang Just make a pull request to contributors.mkdn in android_vendor_resurrection?

**Comment by varund7726** [comment]
@TheNoFace  in packages apps Settings

**Comment by akhilnarang** [comment]
@thenoface
There's a device maintainers string file in res/values
Also add in res/XML device maintainer fragments

**Comment by TheNoFace** [comment]
@akhilnarang @varund7726 So, adding my name in device maintainer list is all I can do? Isn't there any nightlies for official devices? Then what is OTA Center for?

**Pull request merged**
