### PR TITLE
Notification drawer brightness slider switch

### PR DESCRIPTION
**Pull request by apascual89**
Original commit:
https://github.com/temasek/android_packages_apps_Settings/commit/b53565b103a09a57f9d90bd58f7464502581234c

### CODE REVIEW

**Comment by varund7726** [comment]
And where is the commit for base?

**Comment by apascual89** [comment]
Base support was already there added by CM a while ago. Working as intended

**Comment by varund7726** [comment]
Ok thanks then

**Comment by apascual89** [comment]
Sure thing !

Glad to contribute

**Comment by varund7726** [comment]
:)

**Pull request merged**
