### PR TITLE
Move Magisk Manager Settings shortcut to below KA settings shortcut, …

### PR DESCRIPTION
**Pull request by ghost**
…westcripp implied

Im going to guess this wont be looked at as my comments were deleted. Here it is I moved it below KA Settings shortcut. I wont be doing anymore merge request.

### CODE REVIEW

**Comment by varund7726** [comment]
Which comments got deleted?

**Comment by westcripp** [comment]
Agreed Which comment got deleted  ?

**Comment by westcripp** [comment]
Ah Varun force pushed to settings .That's why it's deleted don't get it
personally

**Comment by varund7726** [comment]
yeah sorry about that . not done intentionally

**Comment by ghost** [comment]
Thanks guys. I have one last thing I would like you to consider. Ill do the pull request when I am done. It was a request from some of the guys I know use your ROM.

**Pull request merged**
