### PR TITLE
Add Redmi Note 5 Pro Whyred Maintainer

### PR DESCRIPTION
**Pull request by dinhsan2000**
Devices Tree : https://github.com/dinhsan2000/android_device_xiaomi_whyred
Vendor  Tree: https://github.com/dinhsan2000/android_vendor_xiaomi_whyred
Kernel   Tree: https://github.com/dinhsan2000/android_kernel_xiaomi_whyred

### CODE REVIEW

**Comment by varund7726** [comment]
whats your telegram?

**Comment by varund7726** [comment]
You also need to add to fragment

**Comment by varund7726** [comment]
https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/9686023738c3b09feaa547cb3658d6c2bda737e1

**Comment by dinhsan2000** [comment]
I have updated, it is here
My telegram: t.me/san2k
fdac442

**Comment by varund7726** [comment]
Why are codenames similar to https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/6edc6c48fdaace6a69c356a95921df49ef31c044

**Comment by dinhsan2000** [comment]
Close

**Pull request closed without merging**
