### PR TITLE
French Update 7 - Added GA and SAP

### PR DESCRIPTION
**Pull request by ghost**
Just added Gesture Anywhere and System App Remover translation ! :D
I figured out a typing fault at line 1009 (in the english version of the translation) normally it's "Location" but it is written "Loction". Just saying ! 

EDIT: Dammit, i don't know why my text editor deleted the two backspaces at line 973 (d'afficher) and line 978 (d'applications). It would be nice if you could change it when you merge it :)

Have a good day !

### CODE REVIEW

**Comment by xenon92** [comment]
If you find any error in your commit, Make another commit to fix those issues and push that to the same branch as the one you sent pull request from. That new commit will be added to this pull request and both commits will be merged together.

**Comment by xenon92** [comment]
"Location" typo fixed in English. Thanks. :+1:

**Comment by ghost** [comment]
Okay thanks for the tip ! I just fixed it :)
Hope you can merge it soon. :+1:

**Comment by westcripp** [comment]
@madican i forgot to merge your translation updates .sorry mate

**Comment by ghost** [comment]
No problem west ^^ If you could do it now it would be great ! Thanks !

**Comment by westcripp** [comment]
İs there any typo ? İ ll merge but cant test right now

**Comment by ghost** [comment]
Normally i fixed all issues in the strings ;) If there is a problem just say it to me !

**Comment by westcripp** [comment]
ok fixed .thanks mate https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/30e528c21f72792af1d45874b3ad66d9bcd08b5d

**Pull request merged**
