### PR TITLE
revert auto translation import

### PR DESCRIPTION
**Pull request by paradroid12**
Automatic translation import cover the chinese translation

### CODE REVIEW

**Comment by akhilnarang** [comment]
@paradroid12 are the old ones fine?
If so will import old ones to crowdin

**Comment by paradroid12** [comment]
yes, the old one is fine.

**Comment by akhilnarang** [comment]
:+1: ok will import to crowdin soon

**Comment by akhilnarang** [comment]
@paradroid12 imported to crowdin simplified chinese 
Please submit new translations there now 
https://crowdin.com/project/resurrectionremix/
Thanks =)

**Pull request closed without merging**
