### PR TITLE
Add: Oneplus3 Official

### PR DESCRIPTION
**Pull request by dlasdl**
Device Tree : [https://github.com/dlasdl/device_oneplus_oneplus3.git](url)
Vendor : [https://github.com/SuperiorOS-Devices/vendor_oneplus_oneplus3](url)
Kernel : [https://github.com/SuperiorOS-Devices/kernel_oneplus_msm8996](url)

Telegram : @dlasdl
Mail : dineshdlas@live.com

XDA : https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/10-0-resurrection-remix-v8-5-6-t4146273/post83260023#post83260023

### CODE REVIEW

**Comment by varund7726** [comment]
There is already a string here https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/blob/Q/res/values/resurrection_device_maintainers_strings.xml#L192

Why not modify that? Please look carefully or you will cause  build error 

thanks

**Comment by dineshsanker** [comment]
Sir,
Now what will i have to plz accept r give advice

**Comment by dlasdl** [comment]
> There is already a string here https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/blob/Q/res/values/resurrection_device_maintainers_strings.xml#L192
> 
> Why not modify that? Please look carefully or you will cause build error
> 
> thanks

Dear Sir,
Please advice what will i do

**Comment by varund7726** [comment]
Male a new commit and just add your name across the string I marked. Don't add new strings. 
Thank you

**Pull request closed without merging**
