### PR TITLE
Update maintainer for Galaxy Note 3 Qcom

### PR DESCRIPTION
**Pull request by vidwhal**
Previous maintainer has relinquished his role in maintaining and OKed myself to fill the role.

- Update device_maintainers_fragment.xml with device_hlte

- Update resurrection_device_maintainers_strings.xml

### CODE REVIEW

**Comment by vidwhal** [comment]
Currently maintaining an unofficial build thread on XDA:
https://forum.xda-developers.com/galaxy-note-3/development/rom-resurrection-remix-n-v5-8-3-vanilla-t3615227

**Review by varund7726 — COMMENTED** [review]
If device_hlte was already there in the fragment, why add it again? Pls remove it otherwise there will be duplicate preferences

**Comment by vidwhal** [comment]
I think you're mistaken Varun. There is no hlte in the fragment, only the exynos variant (ha3g) which is maintained by someone else. I also noticed hlte maintainer doesn't show in the list in the phone settings, probably because the fragment is missing in the first place...
Cheers.

**Comment by varund7726** [comment]
Ok then

**Pull request merged**
