### PR TITLE
Add Samsung Galaxy S7 maintainer

### PR DESCRIPTION
**Pull request by gwolf2u**
supporting SM-G930F/FD/W8/S/K/L

### CODE REVIEW

**Comment by varund7726** [comment]
What are the bugs present in this build? I hope not major ones

**Comment by varund7726** [comment]
For this device

**Comment by gwolf2u** [comment]
no major bugs 

Calling works
Camera works
Connectivity works (including wifi hotspot)
There are a few tweaks here and there that need to be adjusted, but the rest is all good

**Comment by varund7726** [comment]
ok then

**Comment by Nestade** [comment]
He kanged it from this dev-team...
https://forum.xda-developers.com/s7-edge/development/rom-resurrection-remix-os-nougat-t3528861
https://github.com/8890dev

He didn't even ask the head-maintainer
They were the first providing builds for the S7 and S7 edge and ported AOSP to this devices.
http://download.jesec.io/

**Comment by varund7726** [comment]
@gwolf2u I would like to hear your side of this

**Comment by gwolf2u** [comment]
I just wanted to bring this device to official status as long as there are no crucial bugs in it while also working on fixing the known bugs and also adding support for new features RR added that I've seen are not fully compatible with the S7 since I noticed no one is focusing on that part 
I did sent a message to **jesec**, that is building unofficial, kindly asking to take over building the official version

think I will keep updating RR for LG G5 since there are no complains about my work

**Comment by Nestade** [comment]
If you had asked him before you apply for official, nobody would've been mad.
Quite the reverse! The more devs the better. But just copying his code with almost no modifications isn't very nice. We asked him at Telegram and he doesn't (didn't?) even know you.
I just closed as I don't want to destroy your reputation or something like that and reference seems to take place in here.
I just sent a message to jesec in Telegram - hope he will answer in here - however also try to contact him by yourself if you can get permission or not - but I think you should at least work together and not just do 2 different projects based on his code.

**Comment by jesec** [comment]
My answer is NO. A different build could lead to confusions and difficulties in bug reporting and beta testing.

**Comment by varund7726** [comment]
So all of you please come to a mutual understanding . do I keep @gwolf2u as maintainer or do I revert this commit?

**Comment by akhilnarang** [comment]
What code did he copy?

**Comment by gwolf2u** [comment]
not willing to start anything here so I can agree, please remove me as maintainer 
@jesec will apply to official when time comes

**Comment by varund7726** [comment]
Ok as you guys wish

**Pull request merged**
