### PR TITLE
Add Maintainer For Yu Yunique (jalebi) (1/2)

### PR DESCRIPTION
**Pull request by iamsj7**

### CODE REVIEW

**Comment by iamsj7** [comment]
device fragment already their ..

**Review by varund7726 — COMMENTED** [review]
device_jalebi and rest strings already there.just replace names

**Comment by iamsj7** [comment]
yep!! I didn't noticed thought that it's new..
I will make a new pull then.
Thank you

**Comment by varund7726** [comment]
👍

**Pull request closed without merging**
