### PR TITLE
New fr translation

### PR DESCRIPTION
**Pull request by Seb02859**
Based primarly on Resurrection_packages_apps_Settings/res/values/rr_strings.xml (Revert "AdBlock_1/3" - commit 4c3bcd56ce267095c000b21ded5e1a328f7c86af) and on the old fr translation.

Need a test before merge, because i d'ont know how test it. But i think it's work.

### CODE REVIEW

**Comment by akhilnarang** [comment]
@Seb02859 copy paste file online into xml validator to test

**Comment by akhilnarang** [comment]
@ShevT it was verified by an xml validator, hence I merged it, will check it out

**Comment by ShevT** [comment]
You have tried to compile with your translation?

error: Apostrophe not preceded by \

Before "'" need "\" symbol
e.g. Couleur de l\'étiquette

**Comment by Seb02859** [comment]
westcripp has corrected this, sorry for that. I have not see it, because of many change in the file.

I don't know how compile, so i have make just the xml validation. :s

**Comment by ShevT** [comment]
Yes, I can see that already corrected

**Pull request merged**
