### PR TITLE
Revert "Update lettuce maintainer"

### PR DESCRIPTION
**Pull request by Abhinavgupta371**
Reverts ResurrectionRemix/Resurrection_packages_apps_Se

### CODE REVIEW

**Comment by HassanSardar** [comment]
@Abhinavgupta371 What exactly are you trying to do?

**Comment by Abhinavgupta371** [comment]
I wanna revert it the dev want to still maintain rr so

**Comment by xenreon** [comment]
You even saw what you sent?

**Comment by akhilnarang** [comment]
What?

**Comment by xenreon** [comment]
Guess the previous lettuce maintainer wants to continue,so he sent pr to revert his update and just added a6000 by mistake?

**Comment by Abhinavgupta371** [comment]
Oops by mistake added a6000..i just wanna revert the lettuce commit as he wants to continue

**Comment by HassanSardar** [comment]
@Abhinavgupta371 Revert already looks ugly in the very start of PRs.
Close this PR and create a new one, without reverting. Just update the name to old maintainer and set the title as "Update lettuce maintainer"

**Pull request closed without merging**
