### PR TITLE
battery bar color

### PR DESCRIPTION
**Pull request by pavlaras**
not sure about lines 146-157. check my overall correction before accepting it.

### CODE REVIEW

**Comment by varund7726** [comment]
Great settings is OK.where is fw base part?

**Comment by varund7726** [comment]
And authorship needs to be intact

**Comment by pavlaras** [comment]
sorry for late answer. i didnt write an author in battery color script because there isn't one. i just used imagination to add color to our statusbar because i like it. i used the MM rr remix battery bar for the idea.

**Comment by varund7726** [comment]
OK I added battery bar colors anyways .have a look at the source

**Pull request closed without merging**
