### PR TITLE
Add Pixel 2 (Walleye)

### PR DESCRIPTION
**Pull request by ghost**
Device tree: https://github.com/gibranmather/android_device_google_muskie
Kernel: https://github.com/LineageOS/android_kernel_google_wahoo

### CODE REVIEW

**Comment by varund7726** [comment]
Clear conflicts

**Comment by ghost** [comment]
Conflicts cleared

**Comment by varund7726** [comment]
Please send me your telegram ID

**Comment by ghost** [comment]
@Giblyat

**Pull request merged**
