### PR TITLE
Add Exynos 9810. S9+, S9 and Note 9 Maintainer

### PR DESCRIPTION
**Pull request by garett09**
Maintainer name: Adrian Sian Telegram name: https://t.me/garett_09
Device Tree: https://github.com/adriansian/android_device_samsung_universal9810-common
https://github.com/adriansian/android_device_samsung_star2lte
https://github.com/adriansian/android_device_samsung_starlte
https://github.com/adriansian/android_device_samsung_crownlte

Kernel tree: https://github.com/synt4x93/android_kernel_samsung_universal9810

### CODE REVIEW

**Comment by garett09** [comment]
Update: built fine, tested and booted well.

**Comment by varund7726** [comment]
whats your telegram?

**Comment by varund7726** [comment]
https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/9686023738c3b09feaa547cb3658d6c2bda737e1

Add to fragment too otherwise name wont display

**Comment by garett09** [comment]
telegram: garett_09 okay will add!

**Pull request closed without merging**
