### PR TITLE
Update maintainer for LG G3 (D-855)

### PR DESCRIPTION
**Pull request by frazerecho**
Marchetto has left this device, I'm taking over. Uploading my build as I write this. Will have thread ready in a bit. Talked to Vatsal about it. Varun not replying on Slack. I maintain Moto G 4G as well. And I've talked to Marchetto too.

### CODE REVIEW

**Comment by varund7726** [comment]
We do have someone in line to maintain d855.
And I dont see PMS on slack .either post in our group or pm me on hangouts or gmail. 
Nevertheless , somebody already filled the spot.  If he backs out , I will reopen this request

**Comment by frazerecho** [comment]
Brother, I sent you a PM on slack yesterday evening (your time)

You're handle is varund7726 na?

**Comment by varund7726** [comment]
Sorry I told you I dont check PMs on slack
Its clearly written in about RR in the ROM to PM me on hangouts 
Sorry dude

screenshot_20170123-182725

**Comment by frazerecho** [comment]
Hahahaha my bad!

No worries, I know the guy who stepped up is more capable than me. ;)

If he backs out, I'm here!

#Peace

**Comment by varund7726** [comment]
No problem I'll keep you posted

**Pull request closed without merging**
