### PR TITLE
Add Lenovo Vibe K5 (A6020)

### PR DESCRIPTION
**Pull request by jhenrique09**
Signed-off-by: jhenrique09 <jhenrique09.mcz@hotmail.com>

### CODE REVIEW

**Comment by varund7726** [comment]
Hold up guys , don't merge this yet .need to cofirm with someone else first

**Comment by varund7726** [comment]
Ok done

**Comment by jhenrique09** [comment]
Thanks dude

**Comment by ghost** [comment]
https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/dea4c30d2bc662ad3fb02c88b18d543dc8f6bf69#diff-1532e37bb5d98280645443c370aa50bc

**Comment by ghost** [comment]
Перемещение на этот репо пожалуй ста

**Comment by akhilnarang** [comment]
@DmitriySemenov what? Please talk in english, and don't go around commenting on ancient pull requests.

**Pull request merged**
