### PR TITLE
Add Maintainer for Nexus 9, Nexus 10, Moto X Pure, LG G2, Galaxy S3 (all variants), and Touchpad to the mix

### PR DESCRIPTION
**Pull request by sixohtew**
Flounder, Manta, Clark, VS980, D2LTE, and Tenderloin need maintainer updates

### CODE REVIEW

**Comment by varund7726** [comment]
Change i9300 too

**Comment by sixohtew** [comment]
added i9300 to the mix

**Comment by sixohtew** [comment]
hope we can get this merged before someone else makes a pull request and i have to make more changes. i also cleaned up the code to make it more uniform

**Comment by varund7726** [comment]
Mate what are you doing? I9300 is already maninatained by me not you 
Change that . 
And I told you to correct i9300 string .your making a very messy patch dude .

**Comment by sixohtew** [comment]
sorry, i didnt know what you meant... i fixed the i9300 string and made sure everything is correct.. and ive cleaned up a lot of the repo, hope this is all we need

**Comment by sixohtew** [comment]
@varund7726 check it out and let me know

**Comment by akhilnarang** [comment]
@sixohtew please resubmit it all as 1 commit

**Pull request closed without merging**
