### PR TITLE
Add z2 tablet maintainer

### PR DESCRIPTION
**Pull request by opendata26**

### CODE REVIEW

**Comment by varund7726** [comment]
Need device_castor and device_castor_summary in res/xml/device_maintainers_fragment.xml as well please

**Comment by opendata26** [comment]
Done

**Comment by akhilnarang** [comment]
Rebase the patch please

**Comment by opendata26** [comment]
Done

**Comment by varund7726** [comment]
No wait there is something wrong here .look at the number of changes with your patch .hang on I'll do it

**Pull request closed without merging**
