### PR TITLE
Add Maintainer for ZTE BLADE A610 (a610)

### PR DESCRIPTION
**Pull request by mosya234**

### CODE REVIEW

**Comment by AndropaX** [comment]
Wait
https://github.com/mosya234/android_device_zte_blade_a610/blob/master/lineage.mk#L38
You're overriding languages included in rom, this won't be approved...

**Comment by mosya234** [comment]
I fixed.

**Comment by mosya234** [comment]
Fixing.  23.07.2017, 13:59, "AndropaX" <notifications@github.com>:Waithttps://github.com/mosya234/android_device_zte_blade_a610/blob/master/lineage.mk#L38You're overriding languages included in rom, this won't be approved...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mosya234** [comment]
By mistake I pressed, sorry

**Comment by mosya234** [comment]
@varund7726 Hello. I was wondering how to release a firmware RR-N to make (and upload them on the website https://sourceforge.net/projects/resurrectionremix/files and release the OTA update?

**Comment by varund7726** [comment]
Send me your email id

**Comment by mosya234** [comment]
mosya234@yandex.ru

**Pull request merged**
