### PR TITLE
Update rr_strings.xml

### PR DESCRIPTION
**Pull request by razor84**
Please merged. Thank you

### CODE REVIEW

**Comment by varund7726** [comment]
Line 1302 column 80.mismatched tag
Validate syntax on
http://www.w3schools.com/xml/xml_validator.asp

**Comment by razor84** [comment]
I did not know what to do? Can you help?

**Comment by akhilnarang** [comment]
Check line 1302
<b> </b> 
not <b> <b>

**Comment by razor84** [comment]
I turned into the original

**Comment by akhilnarang** [comment]
verify xml

**Comment by razor84** [comment]
How should I do?

**Pull request merged**
