### PR TITLE
Remove Z010D maintainer  ;( 

### PR DESCRIPTION
**Pull request by Anandnv**
Fek Collage ;(

### CODE REVIEW

**Comment by varund7726** [comment]
I would recommend just removing the name from strings

**Comment by Anandnv** [comment]
@varund7726  
There is only 3 devs for Z010D
And the other 2 shitheads won't maintain or build ROMs..
So its better to remove whole data

**Comment by Anandnv** [comment]
And if I remove only from string.. Then will face build errors

**Comment by varund7726** [comment]
No if you keep string name but remove string value , there will be no build errors

**Comment by varund7726** [comment]
Umm so you decided to create your own ROM .that's why you left  .at least you could've been honest about it

**Comment by Anandnv** [comment]
@varund7726   lol .. i applied for maintainership during the work.. thats not the problem.
i dont have a server to build+ using old pc with core2duo 2 gb ram
if i manages to get a server with full acces i will build for sure. currently doing unofficial builds.  using aimrom server 

and also @audahadi is doing weekly builds for our device. soooo....

**Comment by varund7726** [comment]
OK then .

**Pull request merged**
