### PR TITLE
Update maintainers for clark, flounder, manta, and tenderloin.

### PR DESCRIPTION
**Pull request by sixohtew**
Still needed to make one change

### CODE REVIEW

**Review by sixohtew — COMMENTED** [review]
Still needed to make one change

**Comment by sixohtew** [comment]
add Maintainer for Moto X Pure (clark), HTC Nexus 9 (flounder), Samsung Nexus 10 (manta), and HP Touchpad (tenderloin)

**Comment by varund7726** [comment]
Add the devices in fragment as well .the new ones .can't merge otherwise

**Comment by sixohtew** [comment]
where would i find that fragment file?

**Comment by sixohtew** [comment]
updated device_maintainers_fragment.xml

**Comment by varund7726** [comment]
Why are you adding lenovo category again?

**Comment by sixohtew** [comment]
I believe it's because I accidentally deleted it

**Comment by varund7726** [comment]
I don't see it deleted .and what about the Samsung string?

**Comment by sixohtew** [comment]
i added the nexus 10 (manta) as well. hope this can be merged soon

**Comment by varund7726** [comment]
@sixohtew I'm still waiting for you to add nexus 10 in fragment and make the corrections I asked you to do on the commit .check the commits please .otherwise I can't merge

**Comment by sixohtew** [comment]
@varund7726 nexus 10 is in fragments, as manta, and what other corrections do i need to fix

**Comment by varund7726** [comment]
Device _Samsung_title should be device_HP_title

**Comment by sixohtew** [comment]
all fixed, and i added the galaxy s3 all variants to the list as well @varund7726

**Comment by varund7726** [comment]
Ok 👍

**Comment by varund7726** [comment]
There are still some conflicts so can't merge .pull the main branch and modify this pull request

**Comment by akhilnarang** [comment]
Oops got merged by mistake. Reset it. Please submit one without the conflicts

**Pull request merged**
