### PR TITLE
Added Xiaomi Mi A1 and Mi 9t/K20 maintainer

### PR DESCRIPTION
**Pull request by mountaser**

### CODE REVIEW

**Comment by varund7726** [comment]
Build booted and tested?

**Comment by mountaser** [comment]
It will tomorrow 😉 am out to party now and just saw the good news but don't worry both builds will be ready tomorrow it's not my first RR build xD

**Comment by varund7726** [comment]
https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/f6cc7a7c191972e5fa8f508a8fe77202dee1235

Don't forget to add in fragment

**Comment by varund7726** [comment]
any update on this?

**Pull request closed without merging**
