### PR TITLE
update zuk z2 maintianer

### PR DESCRIPTION
**Pull request by MRTHAKER**
*adding support for zuk z2 plus.

### CODE REVIEW

**Comment by varund7726** [comment]
Add this in fragment as well

**Comment by MRTHAKER** [comment]
Fragment??

**Comment by varund7726** [comment]
Yes in res/xml/device_maintainers_fragment.xml

Look at the other pull requests maintainers have done .youll come to know

**Comment by MRTHAKER** [comment]
res/xml/device_maintainers_fragment.xml

i did pull request for the file you mentioned.

**Comment by AndropaX** [comment]
Typo here, you must change ham to z2

**Comment by MRTHAKER** [comment]
i don't understand what you just said bro??

**Comment by varund7726** [comment]
Mate can you make this in one pull request? Change of both files .we expect our maintainers to know a little bit about github so this is just a small test to see if you know anything about git push .

**Comment by MRTHAKER** [comment]
Ohh all in one pull request I thought I have to make separate pull request
for both files,okay I do  that.

**Pull request closed without merging**
