### PR TITLE
Update resurrection_device_maintainers_strings.xml

### PR DESCRIPTION
**Pull request by sixohtew**
add Pixel 2 XL to the mix

### CODE REVIEW

**Comment by varund7726** [comment]
@bdogg718k Aren’t you maintaining this?

**Comment by sixohtew** [comment]
He came out with an official build the same day I did...I don't think he's actively maintaining the pixel 2 xl

**Comment by varund7726** [comment]
But he is on the RR dev team so I guess he has the priority for this device

**Comment by sixohtew** [comment]
ive been on the dev team for quite some time, i compile for the galaxy s3, flounder, manta, and clark

**Comment by varund7726** [comment]
Not on the RR dev team though ;)

**Comment by sixohtew** [comment]
I was told I was, he has not updated the ROM since he first came out with it on the 12th.... I've been making builds for a while but I have not released them because you guys refuse to make me the official maintainer

**Comment by sixohtew** [comment]
screenshot from 2018-03-23 15-42-10
back when i was building for many devices......

**Comment by bdogg718k** [comment]
Been busy with work. Am updating official thread this weekend. Was waiting till we updated rom source a lil.

**Comment by sixohtew** [comment]
Alright I'll leave it be I guess

**Comment by varund7726** [comment]
@sixohtew I understand your making weekly/daily updates but frequent updates doesn't necessarily means anything has changed in the source. Everything is almost the same since the past couple of weeks anyways

**Comment by sixohtew** [comment]
I also use commits not yet merged...and that's why mine is experimental

**Comment by varund7726** [comment]
If your modifying the source then you can't be official :)

**Pull request closed without merging**
